kind: Deployment
apiVersion: apps/v1
metadata:
  name: secret-1-demo
  namespace: dev
spec: 
  replicas: 1
  selector: 
    matchExpressions:
    - key: app
      operator: In
      values: ["secret-1-demo"]
  template:
    metadata:
      labels:
        app: secret-1-demo
    spec: 
      containers: 
      - name: nginx
        image: nginx:1.21.5
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /
            port: 80
        envFrom:
        - prefix: MINI_PROGRAM_
          secretRef: 
            name: secret-1-demo
