---

apiVersion: v1
kind: Pod
metadata:
  name: demo1-empdir
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: logs
      mountPath: /var/log/nginx
  - name: busybox
    image: busybox
    command: 
    - /bin/sh
    - -c
    - |
      sleep infinite
    volumeMounts:
    - name: logs
      mountPath: /logs
  volumes:
  - name: logs
    emptyDir: {}
    
