kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: stateful-demo1
spec:
  serviceName: stateful-demo1
  replicas: 3
  selector:
    matchLabels:
      app: stateful-demo1
  template:
    metadata: 
      labels:
        app: stateful-demo1
    spec: 
      containers:
      - name: nginx
        image: nginx:1.21.6
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: log
          mountPath: /var/log/nginx
  volumeClaimTemplates: 
  - metadata: 
      name: log
    spec:
      resources:
        requests: 
          storage: 10Mi
      accessModes:
      - ReadWriteOnce

