--- 

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob
  namespace: dev
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec: 
          containers:
          - name: busybox
            image: busybox
            command:
            - /bin/sh
            - -c 
            - |
              date >> /tmp/out
          restartPolicy: Never
