---

apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-job-2
  namespace: dev
spec:
  completions: 4
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: busybox
        image: busybox
        command:
        - /bin/sh
        - -c 
        - for i in 9 8 7 6 5 4 3 ; do echo $i; sleep 3; done
        
