---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity: 
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs: 
    server: 10.0.0.10
    path: /mnt/pv1
    
  
--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.10
    path: /mnt/pv2
  
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.10
    path: /mnt/pv3

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv4
spec: 
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.10
    path: /mnt/pv4
  
--- 
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv5
spec:
  capacity: 
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.10 
    path: /mnt/pv5

---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv6
spec: 
  capacity: 
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs: 
    server: 10.0.0.10
    path: /mnt/pv6

