kind: LimitRange
apiVersion: v1
metadata:
  name: lr-1-demo
  namespace: dev-quota
spec:
  limits:
  - type: Pod
    min:
      cpu: 50m
      memory: 5Mi
    max:
      cpu: 1
      memory: 2Gi
  - type: Container
    defaultRequest:
      cpu: 100m
      memory: 50Mi
    default: 
      cpu: 500m
      memory: 500Mi
    min:
      cpu: 50m
      memory: 50Mi
    max:
      cpu: 1
      memory: 1Gi
