kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ps-reader
rules:
- apiGroups: [""]
  resources: ["services", "persistentvolumes", "pods"]
  verbs: ["list", "create", "delete", "update", "get", "watch"]
  
