kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crb-1-demo
subjects:
- kind: ServiceAccount
  name: ps-reader
  namespace: bar
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ps-reader

